server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kancelaria
    username: postgres
    password: projektanto
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true
      database: postgresql
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      enabled: true